name: Build APK

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: flutter-packages
    
    - name: Install Dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk -t lib/ui_main.dart --release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: |
          build/app/outputs/apk/release/*.apk
          build/app/outputs/apk/release/output-metadata.json
